name: Validate JSON Schemas

on:
  push:
    branches: ["main"]
    paths:
      - "schemas/**"
      - ".github/workflows/validate-schemas.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "schemas/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Schemas
        uses: docker://ghcr.io/ajv-validator/ajv-cli:8.2.0
        with:
          args: validate -s schemas/**/v*/schema.json -d schemas/**/v*/test/valid/*.json
